@HospitalAiChatBot_HostAddress = http://localhost:5045

GET {{HospitalAiChatBot_HostAddress}}/api/health

###

POST {{HospitalAiChatBot_HostAddress}}/api/qa
Content-Type: application/json

"куестион"

###

POST {{HospitalAiChatBot_HostAddress}}/api/feedback
Content-Type: application/json

"нормально"

###

GET {{HospitalAiChatBot_HostAddress}}/api/scrape/callcentercontacts

###

GET {{HospitalAiChatBot_HostAddress}}/api/scrape/openinghours

###

POST {{HospitalAiChatBot_HostAddress}}/api/specialistqa
Content-Type: application/json

"вопрос"

###